[project]
name = "huggingface-openai-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "M. Oly Mahmud", email = "mugdhodzs38@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.15.0",
    "fastapi[standard]>=0.142.2",
    "torch>=2.14.1",
    "transformers>=5.18.0",
]

[project.scripts]
huggingface-openai-api = "huggingface_openai_api:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]
